language: node_js

node_js:
- node

before_install:
  - chmod +x frontend.sh

jobs:
  include:
    - stage: deploy_frontend
      script: ./deploy/frontend.sh
    - stage: deploy_functions
      script: ./deploy/functions.sh